# to test
# docker run -ti -v "$PWD:$PWD" -w "$PWD" goreleaser/goreleaser:latest release --snapshot --rm-dist
project_name: pind

before:
  hooks:
    - go mod download

release:
  draft: true

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
#      - windows
#      - darwin
    flags:
      - -trimpath
    ldflags:
      # omit symbol table and debug information
      - -s -w
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser
checksum:
  name_template: "checksums.txt"

archives:
  - files:
      # skip all other files
      - none*
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    # pind_1.0.1_linux_amd64.tar.gz
    # pind_1.0.1_macos_arm64.zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- .Arch }}

#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - "^Merge"

brews:
  - skip_upload: auto
    repository:
      owner: pnsafonov
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/pnsafonov/pind
    description: pind - daemon for pinning cpu cores to processes
    license: MIT
    test: |
      system "#{bin}/pind --version"
