# to test
# docker run -ti -v "$PWD:$PWD" -w "$PWD" goreleaser/goreleaser:latest release --snapshot --rm-dist
project_name: pind

before:
  hooks:
    - go mod download

#release:
#  draft: false

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
#      - windows
#      - darwin
    flags:
      - -trimpath
    ldflags:
      # -w turns off DWARF debugging information
      # -s turns off generation of the Go symbol table
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser
checksum:
  name_template: "checksums.txt"

archives:
  - files:
      # skip all other files
      - none*
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    # pind_1.0.1_linux_amd64.tar.gz
    # pind_1.0.1_macos_arm64.zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- .Arch }}
